// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { FreelanceEscrow$Type } from "./FreelanceEscrow";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["FreelanceEscrow"]: FreelanceEscrow$Type;
    ["contracts/Escrow.sol:FreelanceEscrow"]: FreelanceEscrow$Type;
  }

  interface ContractTypesMap {
    ["FreelanceEscrow"]: GetContractReturnType<FreelanceEscrow$Type["abi"]>;
    ["contracts/Escrow.sol:FreelanceEscrow"]: GetContractReturnType<FreelanceEscrow$Type["abi"]>;
  }
}
